"""Canonical Runtime Action Contracts and Data Models."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4
from pydantic import BaseModel, ConfigDict, Field

from agent.tools.models import ReversibilityClass, RiskLevel


class ActionStatus(str, Enum):
    PROPOSED = "PROPOSED"
    VALIDATED = "VALIDATED"
    ASSESSED = "ASSESSED"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    EXECUTING = "EXECUTING"
    COMMITTED = "COMMITTED"
    REVERTED = "REVERTED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class ActionProposal(BaseModel):
    """Untrusted tool proposal generated by the LLM planner."""

    proposal_id: str = Field(default_factory=lambda: str(uuid4()))
    session_id: str = Field(..., description="UUID of the active session")
    tool_name: str = Field(..., description="Name of the requested tool")
    arguments: Dict[str, Any] = Field(default_factory=dict, description="Raw arguments proposed by LLM")
    reasoning: str = Field(default="", description="LLM intent and explanation")
    proposed_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    model_config = ConfigDict(frozen=True)


class ToolContext(BaseModel):
    """Runtime context provided to tool execution and verification handlers."""

    session_id: str
    workspace_root: str
    step_index: int
    environment_vars: Dict[str, str] = Field(default_factory=dict)

    model_config = ConfigDict(frozen=True)


class VerificationResult(BaseModel):
    """Result of post-action invariant verification checks."""

    passed: bool
    verification_type: str = Field(default="DETERMINISTIC_SYNTAX_OR_LINTER")
    output: str = Field(default="")
    errors: List[str] = Field(default_factory=list)
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    model_config = ConfigDict(frozen=True)


class InverseOperationReference(BaseModel):
    """Inverse recipe for reversing an executed action."""

    inverse_tool_name: str
    arguments: Dict[str, Any] = Field(default_factory=dict)
    execution_order: int = Field(default=1)

    model_config = ConfigDict(frozen=True)


class ActionResult(BaseModel):
    """Raw execution result of a tool execution attempt."""

    success: bool
    output: Any = None
    error_message: Optional[str] = None
    execution_time_ms: float = 0.0

    model_config = ConfigDict(frozen=True)


class RiskAssessment(BaseModel):
    """Runtime risk engine evaluation result."""

    score: RiskLevel
    rationale: str
    requires_approval: bool
    factors: List[str] = Field(default_factory=list)

    model_config = ConfigDict(frozen=True)


class Action(BaseModel):
    """Authoritative, runtime-validated action node in REWIND."""

    action_id: str = Field(default_factory=lambda: str(uuid4()))
    session_id: str
    step_index: int
    tool_name: str
    arguments: Dict[str, Any]
    reasoning: str = ""
    expected_effect: str = ""
    risk_assessment: RiskAssessment
    reversibility_class: ReversibilityClass
    dependencies: List[str] = Field(default_factory=list)
    checkpoint_id: Optional[str] = None
    pre_state_ref: Dict[str, Any] = Field(default_factory=dict)
    post_state_ref: Dict[str, Any] = Field(default_factory=dict)
    inverse_ref: Optional[InverseOperationReference] = None
    verification_ref: Optional[VerificationResult] = None
    status: ActionStatus = ActionStatus.PROPOSED
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    model_config = ConfigDict(frozen=False)
